// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJyC4zM33LiLmJmMA2TrxBz4RzMw_Shk0',
    appId: '1:230627925686:web:8337f10e081817bcb59017',
    messagingSenderId: '230627925686',
    projectId: 'housingroyce-147b3',
    authDomain: 'housingroyce-147b3.firebaseapp.com',
    storageBucket: 'housingroyce-147b3.appspot.com',
    measurementId: 'G-NLT5HLYH48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfXL0-9ix1O1Q5lMjVfcmdvhfYuByEryM',
    appId: '1:230627925686:android:a7dc68cc833e4290b59017',
    messagingSenderId: '230627925686',
    projectId: 'housingroyce-147b3',
    storageBucket: 'housingroyce-147b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvMrx2NFHQRNNGKUsBjXNFWo53QJcxjKs',
    appId: '1:230627925686:ios:eec69b7adcd5a1d3b59017',
    messagingSenderId: '230627925686',
    projectId: 'housingroyce-147b3',
    storageBucket: 'housingroyce-147b3.appspot.com',
    iosBundleId: 'com.ownhouse.customer',
  );

}